#!/bin/bash
# Copyright 2021 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later


bye() {
    whiptail --title "Hello Wazo HELP / Mailjet" --msgbox "Your SMTP configuration has been modified\nHave a nice day :-) Wazo Support." 10 60
}

update_smtp_origin() {
    SMTP_Origin=$(whiptail --title "Hello Wazo HELP / Modify Origin" --inputbox "Please write your new SMTP Domain (ex.: domain.tld | Declare in Mailjet):" 13 60 3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
      {
          echo -e "XXX\n0\nAdd in DB, Please Wait... \nXXX"
          sudo -u postgres psql asterisk -c "UPDATE mail SET origin='$SMTP_Origin', mydomain='$SMTP_Origin';";

          echo -e "XXX\n50\nAdd $SMTP_Origin in DB... Done.\nXXX"
          sleep 0.5

      } | whiptail --gauge "Wait Please" 6 60 0

    fi

    update_canonical

}

update_canonical() {
    Canonical=$(whiptail --title "Hello Wazo HELP / Modify Canonical" \
      --inputbox "Please write user part of mail declare in Mailjet (ex.: noreply):" 13 60 3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        {
            echo -e "XXX\n0\nAdd in DB, Please Wait... \nXXX"
            sudo -u postgres psql asterisk -c "UPDATE mail SET canonical='root $Canonical\nasterisk $Canonical\nwazo-agid $Canonical\nwazo-auth $Canonical\nwazo-amid $Canonical\nmunin $Canonical\nwazo $Canonical';";

            echo -e "XXX\n50\nAdd in DB... Done.\nXXX"
            sleep 0.5

        } | whiptail --gauge "Wait Please" 6 60 0
    fi

    update_relayhost

}

update_relayhost() {
    Relayhost=$(whiptail --title "Hello Wazo HELP / Modify relayhost" \
      --inputbox "Please write Mailjet relay host with port (ex.: in-v3.mailjet.com:587):" 13 60 3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        {
            echo -e "XXX\n0\nAdd in DB, Please Wait... \nXXX"
            sudo -u postgres psql asterisk -c "UPDATE mail SET relayhost='$Relayhost';";

            echo -e "XXX\n50\nAdd in DB... Done.\nXXX"
            sleep 0.5

        } | whiptail --gauge "Wait Please" 6 60 0
    fi

    config_mailjet_login $Relayhost

}

config_mailjet_login() {
    Name=$(whiptail --title "Hello Wazo HELP / Mailjet" --inputbox "Mailjet API username:" 10 60 3>&1 1>&2 2>&3)
    Pass=$(whiptail --title "Hello Wazo HELP / Mailjet" --passwordbox "Mailjet API password" 10 60 3>&1 1>&2 2>&3)
    Relay=$(whiptail --title "Hello Wazo HELP / Mailjet" --inputbox "Mailjet Relay Host" 10 60 $1 3>&1 1>&2 2>&3)
    Account=$(whiptail --title "Hello Wazo HELP / Mailjet" --inputbox "Mailjet Mail (ex.: noreply@domain.tld" 10 60 3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
     xivo-create-config
     xivo-update-config
     create_wazo_template $Name $Pass $Relay $Account
    else
     bye
    fi
}

configure_main_cf_template() {
    echo "
# Add by wazo-smtp-mailjet
smtp_sender_dependent_authentication = yes
sender_dependent_relayhost_maps = hash:/etc/postfix/sender_relay
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd" >> /etc/xivo/custom-templates/postfix/etc/postfix/main.cf

}

check_if_main_cf_template_already_exist() {
    if grep wazo-smtp-mailjet /etc/xivo/custom-templates/postfix/etc/postfix/main.cf 2>&1 > /dev/null
    then
        return 1
    fi

    return 0
}

create_wazo_template() {
    mkdir -p /etc/xivo/custom-templates/postfix/etc/postfix/
    cp /etc/postfix/main.cf /etc/xivo/custom-templates/postfix/etc/postfix/
    echo $4 $3 > /etc/xivo/custom-templates/postfix/etc/postfix/sender_relay
    echo $3 $1:$2 > /etc/xivo/custom-templates/postfix/etc/postfix/sasl_passwd
    chmod 600 /etc/xivo/custom-templates/postfix/etc/postfix/sasl_passwd
    chown root:root /etc/xivo/custom-templates/postfix/etc/postfix/sasl_passwd
    postmap /etc/xivo/custom-templates/postfix/etc/postfix/sender_relay
    postmap /etc/xivo/custom-templates/postfix/etc/postfix/sasl_passwd

    check_if_main_cf_template_already_exist
    if [ $? > 0 ]
    then
        configure_main_cf_template
    fi

    final_step
}

final_step() {
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
       {
            echo -e "XXX\n50\nCreate new config... \nXXX"
            xivo-create-config

            echo -e "XXX\n100\nCreate Config... Done.\nXXX"
            sleep 0.5

            echo -e "XXX\n50\nUpdate new config... \nXXX"
            xivo-update-config

            echo -e "XXX\n100\nUpdate Config... Done.\nXXX"
            sleep 0.5

        } | whiptail --gauge "Wait Please" 6 60 0

        bye

    fi
}

# Main
update_smtp_origin
